# Generated by Django 4.2 on 2023-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('year', models.CharField(max_length=12)),
                ('runtime', models.CharField(max_length=12)),
                ('rating', models.CharField(max_length=12)),
                ('genre', models.CharField(max_length=64)),
                ('image', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('director', models.CharField(max_length=64)),
                ('stars', models.CharField(max_length=128)),
            ],
        ),
    ]
